# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.2204.58.yaml run test
version: "3"

services:

  runtime-setup:
    image: swift-nio-oblivious-http:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-nio-oblivious-http:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/swift-nio-oblivious-http:z
    working_dir: /swift-nio-oblivious-http

  soundness:
    <<: *common
    command: /bin/bash -xcl "swift -version && uname -a && ./scripts/soundness.sh"

  test:
    <<: *common
    command: /bin/bash -xcl "swift $${SWIFT_TEST_VERB-test} $${WARN_AS_ERROR_ARG-} $${SANITIZER_ARG-} $${IMPORT_CHECK_ARG-}"

  # util

  shell:
    <<: *common
    entrypoint: /bin/bash
