name: PR label

permissions:
  contents: read

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  semver-label-check:
    name: Semantic version label check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Check for Semantic Version label
        uses: apple/swift-nio/.github/actions/pull_request_semver_label_checker@drop_swift_6_0_adopt_swift_6_3
